# This workflow will build a Java project with Maven

name: Java Appium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [default]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v2
      with:
       node-version: '12'
    - run: |
            npm install -g appium@v1.20.2
            appium -v
            appium &>/dev/null &
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: mvn clean test
      continue-on-error: true
    - name: Copy test execution report
      run: |
        mkdir public
        cp target/cucumber-reports.html public/index.html
    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'